import { StyleSheet } from 'react-native';

import { LedgerColors, LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    sheet: { flex: 1, backgroundColor: colors.bg },
    handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.dashed, alignSelf: 'center', marginTop: 10, marginBottom: 6 },
    sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingBottom: 12 },
    btnCancel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 15, color: colors.muted, padding: 4 },
    sheetTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 16, color: colors.ink },
    headSpacer: { width: 40 },
    body: { paddingHorizontal: 20, paddingBottom: 40, gap: 6 },

    introText: { fontFamily: LedgerFonts.bodyMedium, fontSize: 14, color: colors.ink2, lineHeight: 20, marginBottom: 10 },
    sectionLabel: {
      fontFamily: LedgerFonts.bodyBold,
      fontSize: 12.5,
      color: colors.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      marginTop: 18,
      marginBottom: 8,
    },
    emptyText: { fontFamily: LedgerFonts.body, fontSize: 13, color: colors.muted, paddingVertical: 8 },
    hintText: { fontFamily: LedgerFonts.body, fontSize: 11.5, color: colors.muted, marginBottom: 8 },

    txRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 14,
      padding: 12,
      marginBottom: 8,
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    txRowSelected: { borderColor: colors.ink },
    iconCircle: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    txInfo: { flex: 1 },
    txName: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.ink },
    txMeta: { fontFamily: LedgerFonts.body, fontSize: 11.5, color: colors.muted, marginTop: 1 },
    txAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 14, color: colors.ink },

    subInputRow: { flexDirection: 'row', gap: 8 },
    subInput: {
      flex: 1,
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      fontFamily: LedgerFonts.bodySemiBold,
      fontSize: 14,
      color: colors.ink,
    },
    subAddBtn: {
      paddingHorizontal: 18,
      borderRadius: 12,
      backgroundColor: colors.ink,
      alignItems: 'center',
      justifyContent: 'center',
    },
    subAddBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13.5, color: colors.bg },
    subChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
    subChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.lineLight,
      borderRadius: 14,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    subChipText: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 13, color: colors.ink },
    chipRemoveBtn: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.line,
      alignItems: 'center',
      justifyContent: 'center',
    },

    roundCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 14,
      marginBottom: 10,
      gap: 10,
    },
    roundHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    roundTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: colors.ink },
    roundAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 14, color: colors.ink },

    chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    chip: {
      backgroundColor: colors.lineLight,
      borderRadius: 12,
      paddingVertical: 6,
      paddingHorizontal: 11,
    },
    chipSmall: {
      backgroundColor: colors.lineLight,
      borderRadius: 10,
      paddingVertical: 4,
      paddingHorizontal: 9,
    },
    chipSelected: { backgroundColor: colors.ink },
    chipText: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 12.5, color: colors.ink2 },
    chipTextSmall: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 11, color: colors.ink2 },
    chipTextSelected: { color: colors.bg },

    extraHint: { fontFamily: LedgerFonts.body, fontSize: 11.5, color: colors.muted },
    extraCard: {
      gap: 8,
      padding: 10,
      borderRadius: 12,
      backgroundColor: colors.lineLight,
    },
    extraCardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    extraCardLabel: {
      fontFamily: LedgerFonts.bodyBold,
      fontSize: 11,
      color: colors.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    extraInputRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
    extraLabelInput: {
      flex: 1,
      backgroundColor: colors.card,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      fontFamily: LedgerFonts.bodySemiBold,
      fontSize: 13,
      color: colors.ink,
    },
    extraAmountInput: {
      width: 90,
      backgroundColor: colors.card,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      fontFamily: LedgerFonts.bodySemiBold,
      fontSize: 13,
      color: colors.ink,
      textAlign: 'right',
    },
    extraSubLabel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 11, color: colors.ink2, marginTop: 2 },

    addExtraBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      alignSelf: 'flex-start',
      backgroundColor: colors.lineLight,
      borderRadius: 10,
      paddingVertical: 7,
      paddingHorizontal: 12,
    },
    addExtraBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 12.5, color: colors.ink2 },

    calcBtn: {
      marginTop: 22,
      backgroundColor: colors.ink,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    calcBtnDisabled: { opacity: 0.35 },
    calcBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.bg },

    resultCard: {
      marginTop: 22,
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 18,
      gap: 4,
    },
    resultTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.ink, marginBottom: 8 },
    donutWrap: { width: 180, height: 180, alignSelf: 'center', marginVertical: 8, alignItems: 'center', justifyContent: 'center' },
    donutCenter: { position: 'absolute', alignItems: 'center', gap: 2 },
    donutTotal: { fontFamily: LedgerFonts.headingBold, fontSize: 19, color: colors.ink },
    donutSub: { fontFamily: LedgerFonts.body, fontSize: 11.5, color: colors.muted },

    rankRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 7 },
    rankDot: { width: 9, height: 9, borderRadius: 4.5 },
    rankName: { flex: 1, fontFamily: LedgerFonts.bodySemiBold, fontSize: 13.5, color: colors.ink },
    rankAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 13.5, color: colors.ink },

    copyBtn: {
      marginTop: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: LedgerColors.income,
      borderRadius: 14,
      paddingVertical: 13,
    },
    copyBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: '#fff' },
  });
}
