import { StyleSheet } from 'react-native';

import { LedgerColors, LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 12,
    },
    monthNav: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    monthLabel: { fontFamily: LedgerFonts.headingBold, fontSize: 18, color: colors.ink },
    todayBtn: {
      marginLeft: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: colors.lineLight,
    },
    todayBtnDim: { backgroundColor: 'transparent' },
    todayBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 12, color: colors.ink },
    todayBtnTextDim: { color: colors.mutedLight },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconBtn: {
      width: 112,
      height: 32,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.card,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingHorizontal: 8,
    },
    iconBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 11.5, color: colors.ink },
    pendingBadge: {
      position: 'absolute',
      top: -5,
      right: -5,
      minWidth: 17,
      height: 17,
      borderRadius: 8.5,
      paddingHorizontal: 4,
      backgroundColor: LedgerColors.expense,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.bg,
    },
    pendingBadgeText: { fontFamily: LedgerFonts.bodyBold, fontSize: 10, color: '#fff' },
    content: { flexGrow: 1, paddingHorizontal: 20, paddingBottom: 32, gap: 14 },
    summaryCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: 18,
      paddingVertical: 16,
      paddingHorizontal: 8,
      shadowColor: '#15130F',
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    summaryItem: { flex: 1, alignItems: 'center', gap: 4 },
    summaryLabel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 11, color: colors.muted },
    summaryValue: { fontFamily: LedgerFonts.headingBold, fontSize: 15, color: colors.ink },
    summaryDivider: { width: 1, height: 28, backgroundColor: colors.line },
    calCard: {
      backgroundColor: colors.card,
      borderRadius: 18,
      paddingTop: 14,
      paddingHorizontal: 10,
      paddingBottom: 6,
      shadowColor: '#15130F',
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    weekdayRow: {
      flexDirection: 'row',
      paddingBottom: 8,
      marginBottom: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.lineLight,
    },
    weekdayLabel: {
      flex: 1,
      textAlign: 'center',
      fontFamily: LedgerFonts.bodyBold,
      fontSize: 11,
      color: colors.muted,
    },
    calGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    dayCell: {
      width: `${100 / 7}%`,
      height: 56,
      alignItems: 'center',
      paddingTop: 4,
      gap: 3,
      borderRadius: 10,
    },
    dayCellSelected: { borderWidth: 2, borderColor: LedgerColors.selectedDay, backgroundColor: colors.card },
    dayNum: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 13, color: colors.ink },
    todayBadge: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.ink,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayNum: { fontFamily: LedgerFonts.bodyBold, fontSize: 13, color: colors.bg },
    dayAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 8.5 },
    previewTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 13, color: colors.ink2, paddingHorizontal: 2 },
    emptyText: { fontFamily: LedgerFonts.body, fontSize: 13, color: colors.muted, paddingHorizontal: 2 },
    txRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 12,
      shadowColor: '#15130F',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    catCircle: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
    txMid: { flex: 1, gap: 2 },
    txName: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.ink },
    txMemo: { fontFamily: LedgerFonts.body, fontSize: 12, color: colors.muted },
    txRight: { alignItems: 'flex-end', gap: 2 },
    txAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 14 },
    txTime: { fontFamily: LedgerFonts.body, fontSize: 11, color: colors.muted },
    addRow: {
      borderWidth: 1.5,
      borderColor: colors.dashed,
      borderStyle: 'dashed',
      borderRadius: 16,
      padding: 12,
      alignItems: 'center',
    },
    addRowText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13, color: colors.muted },
  });
}
