import { StyleSheet } from 'react-native';

import { LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    sheet: { flex: 1, backgroundColor: colors.bg },
    handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.dashed, alignSelf: 'center', marginTop: 10, marginBottom: 6 },
    sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingBottom: 12 },
    btnCancel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 15, color: colors.muted, padding: 4 },
    btnSave: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.ink, padding: 4 },
    sheetTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 16, color: colors.ink },
    body: { paddingHorizontal: 20, paddingBottom: 32, gap: 18 },
    previewRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    previewCircle: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
    nameInput: {
      flex: 1,
      fontFamily: LedgerFonts.headingBold,
      fontSize: 18,
      color: colors.ink,
      borderBottomWidth: 1,
      borderBottomColor: colors.line,
      paddingVertical: 6,
    },
    sectionLabel: {
      fontFamily: LedgerFonts.bodyBold,
      fontSize: 12.5,
      color: colors.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      marginBottom: -8,
    },
    paletteRow: { flexDirection: 'row', gap: 12 },
    paletteIconBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.lineLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    paletteIconBtnSelected: { borderWidth: 2, borderColor: colors.ink },
    colorSwatch: { width: 36, height: 36, borderRadius: 18 },
    colorSwatchSelected: { borderWidth: 3, borderColor: colors.ink },
    subInputRow: { flexDirection: 'row', gap: 8 },
    subInput: {
      flex: 1,
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      fontFamily: LedgerFonts.bodySemiBold,
      fontSize: 14,
      color: colors.ink,
      shadowColor: '#15130F',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    subAddBtn: {
      paddingHorizontal: 18,
      borderRadius: 12,
      backgroundColor: colors.ink,
      alignItems: 'center',
      justifyContent: 'center',
    },
    subAddBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13.5, color: '#fff' },
    subChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: -8 },
    subChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.lineLight,
      borderRadius: 14,
      paddingVertical: 6,
      paddingHorizontal: 12,
    },
    subChipText: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 13, color: colors.ink },
    subChipRemove: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.muted },
    deleteRow: { alignItems: 'center', paddingVertical: 10 },
    deleteRowText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13.5, color: colors.expense },
  });
}
