import { StyleSheet } from 'react-native';

import { LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 12,
    },
    monthNav: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    monthLabel: { fontFamily: LedgerFonts.headingBold, fontSize: 18, color: colors.ink },
    todayBtn: {
      marginLeft: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: colors.lineLight,
    },
    todayBtnDim: { backgroundColor: 'transparent' },
    todayBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 12, color: colors.ink },
    todayBtnTextDim: { color: colors.mutedLight },
    content: { paddingHorizontal: 20, paddingBottom: 32, gap: 14 },
    card: {
      backgroundColor: colors.card,
      borderRadius: 18,
      padding: 18,
      shadowColor: '#15130F',
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    summaryTop: { flexDirection: 'row', justifyContent: 'space-between' },
    summaryItem: { gap: 4 },
    summaryLabel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 11.5, color: colors.muted },
    summaryValue: { fontFamily: LedgerFonts.headingBold, fontSize: 16, color: colors.ink },
    deltaRow: {
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.lineLight,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    deltaText: { fontFamily: LedgerFonts.body, fontSize: 12.5, color: colors.ink2 },
    emptyText: { fontFamily: LedgerFonts.body, fontSize: 13, color: colors.muted, paddingTop: 8 },
    sectionTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: colors.ink },
    budgetCaption: { fontFamily: LedgerFonts.bodySemiBold, color: colors.muted, fontSize: 12 },
    budgetOverallRow: { flexDirection: 'row', alignItems: 'baseline', gap: 4 },
    budgetUsed: { fontFamily: LedgerFonts.headingBold, fontSize: 20, color: colors.ink },
    budgetSlash: { fontFamily: LedgerFonts.body, fontSize: 14, color: colors.muted },
    budgetGoal: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.muted },
    progressBg: { height: 8, borderRadius: 4, backgroundColor: colors.lineLighter, overflow: 'hidden', marginTop: 9, marginBottom: 7 },
    progressBgSmall: { height: 6, marginTop: 0 },
    progressFg: { height: '100%', borderRadius: 4 },
    budgetRemain: { fontFamily: LedgerFonts.body, fontSize: 12, color: colors.ink2 },
    budgetRemainBold: { fontFamily: LedgerFonts.bodyBold, color: colors.ink },
    budgetCatList: { gap: 14, marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.lineLight },
    budgetCatHead: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 7 },
    budgetCatName: { flex: 1, fontFamily: LedgerFonts.bodyBold, fontSize: 13, color: colors.ink },
    budgetCatNums: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 12.5, color: colors.ink2 },
    budgetCatRemain: { fontFamily: LedgerFonts.body, fontSize: 11.5, color: colors.muted },
    budgetCatRemainWarn: { color: colors.food, fontFamily: LedgerFonts.bodyBold },
    donutWrap: { width: 180, height: 180, alignSelf: 'center', marginTop: 6, marginBottom: 4, alignItems: 'center', justifyContent: 'center' },
    donutCenter: { position: 'absolute', alignItems: 'center', gap: 2 },
    donutTotal: { fontFamily: LedgerFonts.headingBold, fontSize: 19, color: colors.ink },
    donutSub: { fontFamily: LedgerFonts.body, fontSize: 11, color: colors.muted },
    rankRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9 },
    rankDot: { width: 10, height: 10, borderRadius: 5 },
    rankName: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 13, width: 60, color: colors.ink },
    rankBarBg: { flex: 1, height: 7, borderRadius: 4, backgroundColor: colors.lineLighter, overflow: 'hidden' },
    rankBarFg: { height: '100%', borderRadius: 4 },
    rankAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 12.5, color: colors.ink2, width: 100, textAlign: 'right' },
    trendLegend: { flexDirection: 'row', gap: 16, paddingBottom: 8 },
    legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    legendDot: { width: 8, height: 8, borderRadius: 2 },
    legendText: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 12, color: colors.ink2 },
    trendChart: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', height: 100 },
    trendCol: { alignItems: 'center', gap: 6 },
    trendBars: { flexDirection: 'row', alignItems: 'flex-end', gap: 3, height: 90 },
    bar: { width: 9, borderRadius: 3 },
    trendMonth: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 10.5, color: colors.muted },
  });
}
