import { StyleSheet } from 'react-native';

import { LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 12,
    },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.card,
      alignItems: 'center',
      justifyContent: 'center',
    },
    monthNav: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    monthLabel: { fontFamily: LedgerFonts.headingBold, fontSize: 18, color: colors.ink },
    todayBtn: {
      marginLeft: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: colors.lineLight,
    },
    todayBtnDim: { backgroundColor: 'transparent' },
    todayBtnText: { fontFamily: LedgerFonts.bodyBold, fontSize: 12, color: colors.ink },
    todayBtnTextDim: { color: colors.mutedLight },
    segmented: {
      marginHorizontal: 20,
      marginBottom: 14,
      backgroundColor: colors.lineLight,
      borderRadius: 12,
      padding: 3,
      flexDirection: 'row',
      gap: 2,
    },
    segment: { flex: 1, alignItems: 'center', paddingVertical: 8, borderRadius: 9 },
    segmentActive: {
      backgroundColor: colors.card,
      shadowColor: '#15130F',
      shadowOpacity: 0.12,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    segmentText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13, color: colors.muted },
    segmentTextActive: { color: colors.ink },
    content: { paddingHorizontal: 20, paddingBottom: 32, gap: 16 },
    emptyText: { fontFamily: LedgerFonts.body, fontSize: 13, color: colors.muted, textAlign: 'center', paddingTop: 32 },
    dayGroup: { gap: 8 },
    dayHead: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', paddingHorizontal: 4 },
    dayHeadLeft: { fontFamily: LedgerFonts.bodyBold, fontSize: 12.5, color: colors.muted },
    dayHeadRight: { fontFamily: LedgerFonts.headingBold, fontSize: 12.5 },
    txRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 12,
      shadowColor: '#15130F',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    catCircle: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
    txMid: { flex: 1, gap: 2 },
    txName: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.ink },
    txMemo: { fontFamily: LedgerFonts.body, fontSize: 12, color: colors.muted },
    txRight: { alignItems: 'flex-end', gap: 2 },
    txAmt: { fontFamily: LedgerFonts.headingBold, fontSize: 14.5 },
    txTime: { fontFamily: LedgerFonts.body, fontSize: 11, color: colors.muted },
  });
}
