import { StyleSheet } from 'react-native';

import { LedgerFonts } from '@/constants/ledgerColors';
import type { ColorPalette } from '@/constants/themePalettes';

export const toggleStyles = StyleSheet.create({
  track: { width: 38, height: 22, borderRadius: 11 },
  knob: {
    position: 'absolute',
    top: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
});

export function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    sheet: { flex: 1, backgroundColor: colors.bg },
    handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: colors.dashed, alignSelf: 'center', marginTop: 10, marginBottom: 6 },
    sheetHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingBottom: 12 },
    btnCancel: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 15, color: colors.muted, padding: 4 },
    btnSave: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.ink, padding: 4 },
    sheetTitle: { fontFamily: LedgerFonts.bodyBold, fontSize: 16, color: colors.ink },
    body: { paddingHorizontal: 20, paddingBottom: 32, gap: 16 },
    segmented: { backgroundColor: colors.lineLight, borderRadius: 12, padding: 3, flexDirection: 'row', gap: 2 },
    seg: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 9 },
    segActiveExpense: {
      backgroundColor: '#fff',
      shadowColor: '#15130F',
      shadowOpacity: 0.12,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    segActiveIncome: {
      backgroundColor: '#fff',
      shadowColor: '#15130F',
      shadowOpacity: 0.12,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    segText: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: colors.muted },
    segTextExpense: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: colors.expense },
    segTextIncome: { fontFamily: LedgerFonts.bodyBold, fontSize: 14, color: colors.income },
    amountWrap: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', gap: 4, paddingVertical: 4 },
    amountInput: { fontFamily: LedgerFonts.headingBold, fontSize: 42, padding: 0, minWidth: 60, textAlign: 'right' },
    amountUnit: { fontFamily: LedgerFonts.bodySemiBold, fontSize: 20, color: colors.muted },
    categoryPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.card,
      borderRadius: 16,
      padding: 10,
      shadowColor: '#15130F',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    catCircle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
    categoryPillText: { flex: 1, fontFamily: LedgerFonts.bodySemiBold, fontSize: 14.5, color: colors.ink },
    formCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      shadowColor: '#15130F',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
      overflow: 'hidden',
    },
    formRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.lineLighter,
    },
    formRowLast: { borderBottomWidth: 0 },
    noteRow: { alignItems: 'flex-start' },
    formLabel: { flex: 1, fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.ink },
    formValue: { flex: 1, textAlign: 'right', fontFamily: LedgerFonts.headingMedium, fontSize: 14, color: colors.ink2 },
    memoInput: { flex: 1, fontFamily: LedgerFonts.bodySemiBold, fontSize: 14, color: colors.ink, padding: 0 },
    noteInput: { flex: 1, fontFamily: LedgerFonts.body, fontSize: 13.5, color: colors.ink, padding: 0, minHeight: 40 },
    timePickerWrap: {
      borderBottomWidth: 1,
      borderBottomColor: colors.lineLighter,
      alignItems: 'center',
      paddingBottom: 8,
    },
    deleteRow: { alignItems: 'center', paddingVertical: 10 },
    deleteRowText: { fontFamily: LedgerFonts.bodyBold, fontSize: 13.5, color: colors.expense },
    accessoryBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.lineLight,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: colors.line,
    },
    accessoryNav: { flexDirection: 'row', gap: 20 },
    accessoryDoneText: { fontFamily: LedgerFonts.bodyBold, fontSize: 15, color: colors.income },
  });
}
